//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechMarkupEditor.Assets {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeechMarkupEditor.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Редактор речевой разметки.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        public static string FileChoosingError {
            get {
                return ResourceManager.GetString("FileChoosingError", resourceCulture);
            }
        }

        public static string SelectWavFile {
            get {
                return ResourceManager.GetString("SelectWavFile", resourceCulture);
            }
        }

        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }

        public static string NegativeStartTime {
            get {
                return ResourceManager.GetString("NegativeStartTime", resourceCulture);
            }
        }

        public static string StartAfterEnd {
            get {
                return ResourceManager.GetString("StartAfterEnd", resourceCulture);
            }
        }

        public static string NegativeEndTime {
            get {
                return ResourceManager.GetString("NegativeEndTime", resourceCulture);
            }
        }

        public static string EndBeforeStart {
            get {
                return ResourceManager.GetString("EndBeforeStart", resourceCulture);
            }
        }

        public static string WordRequired {
            get {
                return ResourceManager.GetString("WordRequired", resourceCulture);
            }
        }

        public static string WordEmpty {
            get {
                return ResourceManager.GetString("WordEmpty", resourceCulture);
            }
        }

        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }

        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }

        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }

        public static string EarType {
            get {
                return ResourceManager.GetString("EarType", resourceCulture);
            }
        }

        public static string LeftEar {
            get {
                return ResourceManager.GetString("LeftEar", resourceCulture);
            }
        }

        public static string RightEar {
            get {
                return ResourceManager.GetString("RightEar", resourceCulture);
            }
        }

        public static string NonDichoticTest {
            get {
                return ResourceManager.GetString("NonDichoticTest", resourceCulture);
            }
        }

        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string WordMarkerDialogTitle {
            get {
                return ResourceManager.GetString("WordMarkerDialogTitle", resourceCulture);
            }
        }

        public static string WordsInAudioFile {
            get {
                return ResourceManager.GetString("WordsInAudioFile", resourceCulture);
            }
        }

        public static string AddWord {
            get {
                return ResourceManager.GetString("AddWord", resourceCulture);
            }
        }

        public static string WordTiming {
            get {
                return ResourceManager.GetString("WordTiming", resourceCulture);
            }
        }

        public static string SearchSeries {
            get {
                return ResourceManager.GetString("SearchSeries", resourceCulture);
            }
        }
        public static string TimeWatermark {
            get {
                return ResourceManager.GetString("TimeWatermark", resourceCulture);
            }
        }

        public static string OverlapsWithWords {
            get {
                return ResourceManager.GetString("OverlapsWithWords", resourceCulture);
            }
        }

        public static string SpeechModelNotFound {
            get {
                return ResourceManager.GetString("SpeechModelNotFound", resourceCulture);
            }
        }

        public static string AudioProcessing {
            get {
                return ResourceManager.GetString("AudioProcessing", resourceCulture);
            }
        }

        public static string RecognitionCanceled {
            get {
                return ResourceManager.GetString("RecognitionCanceled", resourceCulture);
            }
        }

        public static string ModelInitError {
            get {
                return ResourceManager.GetString("ModelInitError", resourceCulture);
            }
        }

        public static string FileSaveError {
            get {
                return ResourceManager.GetString("FileSaveError", resourceCulture);
            }
        }

        public static string ExportDialogTitle {
            get {
                return ResourceManager.GetString("ExportDialogTitle", resourceCulture);
            }
        }

        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }

        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }

        public static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }

        public static string NothingToExport {
            get {
                return ResourceManager.GetString("NothingToExport", resourceCulture);
            }
        }

        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }

        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
